import fs from 'node:fs';
const content=JSON.parse(fs.readFileSync(new URL('./content.json',import.meta.url),'utf8'));
const config=JSON.parse(fs.readFileSync(new URL('./site.config.json',import.meta.url),'utf8'));
const routes=['','treinamento-in-company','consultoria-processos-pessoas','recrutamento-nr1','mentoria-wellness-corporate'];
const names=['O Instituto','Treinamento In Company','Consultoria de Processos e Pessoas','R&S + NR-1','Mentoria para Psicólogos'];
const titles=['Instituto Bruna Vilaça — Wellness Corporate',...names.slice(1).map(n=>`${n} | Instituto Bruna Vilaça`)];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.3"/></svg>';
const chevron='<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m4 6 4 4 4-4" stroke="currentColor" stroke-width="1.2"/></svg>';
const whatsapp='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M20 11.7a8 8 0 0 1-11.9 7l-4.6 1.2 1.2-4.5A8 8 0 1 1 20 11.7Z" stroke="currentColor" stroke-width="1.4"/><path d="M9 7.5c-.8 0-1.3.7-1.1 1.8.5 2.7 2.7 4.9 5.4 5.4 1.1.2 1.8-.3 1.8-1.1l-2-1.2-.8.8c-1.5-.6-2.2-1.3-2.8-2.8l.8-.8L9 7.5Z" fill="currentColor"/></svg>';
const urlFor=i=>i?`/${routes[i]}/`:'/';
const contact=i=>`https://wa.me/${config.whatsapp}?text=${encodeURIComponent(i?`Olá, Bruna! Gostaria de conversar sobre ${names[i]} e agendar um diagnóstico.`:'Olá, Bruna! Gostaria de conhecer as soluções do Instituto e agendar uma conversa de diagnóstico.')}`;
const button=(label,i=0,cls='')=>`<a class="button ${cls}" href="${contact(i)}" target="_blank" rel="noopener noreferrer"><span>${esc(label.replace(/\s*→$/,''))}</span>${arrow}</a>`;
const label=s=>`<span class="eyebrow">${esc(s)}</span>`;
const paragraphs=lines=>lines.map(l=>`<p>${esc(l)}</p>`).join('');
const header=i=>`<a class="skip" href="#conteudo">Ir para o conteúdo</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="/" aria-label="Instituto Bruna Vilaça — Início"><img src="/assets/logo-original.png" width="1110" height="285" alt="Instituto Bruna Vilaça"></a><button class="menu-toggle" aria-controls="navegacao" aria-expanded="false" aria-label="Abrir menu"><span></span><span></span></button><nav id="navegacao" aria-label="Menu principal"><a href="/#instituto">O Instituto</a><a href="/#wellness">Wellness Corporate</a><div class="dropdown"><button class="services-toggle ${i?'active':''}" aria-expanded="false" aria-controls="servicos-menu">Serviços ${chevron}</button><div class="dropdown-panel" id="servicos-menu" hidden>${names.slice(1).map((n,j)=>`<a href="${urlFor(j+1)}" ${i===j+1?'aria-current="page"':''}><small>0${j+1}</small>${esc(n)}${arrow}</a>`).join('')}</div></div><a href="/#autoridade">Autoridade</a><a href="#contato">Contato</a></nav>${button('Falar com a especialista',i,'nav-cta')}</div><div class="reading-progress" aria-hidden="true"></div></header>`;
function hero(i){const d=content[i]['01'];return `<section class="hero ${i?'service-hero service-'+i:''}" id="instituto"><div class="hero-inner container"><div class="hero-copy">${i?`<a class="breadcrumb" href="/">Início <span>/</span> ${esc(names[i])}</a>`:''}${label(d[0])}<h1>${esc(d[1])} <em>${esc(d[2])}</em></h1><p class="hero-description">${esc(d[3])}</p>${button(d[4],i)}<div class="hero-notes">${d[5].split('·').map(s=>`<span>${esc(s.trim())}</span>`).join('')}</div></div><figure class="hero-visual"><div class="portrait-frame"><img src="${i===1?'/assets/treinamento.webp':i===2||i===3?'/assets/estrategia.webp':config.heroImage}" alt="${i===1?'Imagem ilustrativa de profissionais reunidos em treinamento':i===2||i===3?'Imagem ilustrativa de uma reunião estratégica':'Bruna Vilaça em seu ambiente de atendimento'}" width="1066" height="1600" fetchpriority="high"><div class="image-shade"></div></div>${!i||i===4?`<figcaption><span class="signature">Bruna Vilaça</span><span>COMPORTAMENTO HUMANO & ESTRATÉGIA</span></figcaption>`:`<figcaption><span>WELLNESS CORPORATE</span><span>0${i} / ${esc(names[i])}</span></figcaption>`}<span class="vertical-note" aria-hidden="true">PESSOAS. PROCESSOS. RESULTADO.</span></figure></div><div class="hero-bottom container"><span>CIÊNCIA DO COMPORTAMENTO. LINGUAGEM DOS NEGÓCIOS.</span><a href="${i?'#contexto':'#wellness'}" aria-label="Conhecer mais">Explore ${arrow}</a></div></section>`}
function wellness(){const d=content[0]['02'];return `<section class="section wellness" id="wellness"><div class="container"><div class="intro-grid reveal"><div>${label('01 / O CONCEITO')}<h2>Wellness Corporate: <em>bem-estar que vira resultado.</em></h2></div><div class="intro-text">${paragraphs(d.slice(1,3))}</div></div><div class="comparison reveal"><div class="comparison-col muted"><h3><span>−</span> NÃO É</h3><ul>${d.slice(4,8).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="comparison-col"><h3><span>+</span> É</h3><ul>${d.slice(9).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></div></section>`}
function footer(i){return `<footer id="contato"><div class="container footer-main"><div class="footer-about"><a href="/" class="brand"><img src="/assets/logo-original.png" alt="Instituto Bruna Vilaça" width="1110" height="285" loading="lazy"></a><p>Wellness Corporate · Consultoria e Mentoria em Pessoas, Processos e Desenvolvimento Organizacional</p></div><div><span class="footer-title">SOLUÇÕES</span>${names.slice(1).map((n,j)=>`<a href="${urlFor(j+1)}">${esc(n)}</a>`).join('')}</div><div><span class="footer-title">CONVERSE COM A ESPECIALISTA</span><a class="footer-phone" href="${contact(i)}" target="_blank" rel="noopener noreferrer">(49) 99966-5854 ${arrow}</a><p>Maravilha-SC<br>Atuação regional e online</p></div></div><div class="container footer-bottom"><span>© 2026 Instituto Bruna Vilaça. Todos os direitos reservados.</span><a href="#conteudo" class="back-top">Voltar ao topo ↑</a></div></footer><a class="whatsapp-float" href="${contact(i)}" target="_blank" rel="noopener noreferrer" aria-label="Falar com Bruna Vilaça pelo WhatsApp">${whatsapp}<span>Falar com a especialista</span></a>`}
function page(i,body){const description=content[i]['01'][3];return `<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#49161f"><title>${esc(titles[i])}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(titles[i])}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='32' fill='%2349161f'/%3E%3Ctext x='32' y='46' text-anchor='middle' fill='%23d6bf8d' font-family='Georgia' font-size='44' font-style='italic'%3EB%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/main.js" defer></script></head><body class="${i?'service-page':'home-page'}">${header(i)}<main id="conteudo">${hero(i)}${body}</main>${footer(i)}</body></html>`}
const cleanBullet=s=>s.replace(/^[·◆]\s*/,'');
function pain(i){const d=content[i][i?'02':'03'];const bullets=d.filter(x=>/^[·◆]/.test(x));const prose=d.slice(1,d.findIndex(x=>/^[·◆]/.test(x)));return `<section class="section pain" id="contexto"><div class="container"><div class="pain-grid"><div class="pain-intro reveal">${label(i?'01 / O CENÁRIO':'02 / OS SINAIS')}<h2>${esc(d[0])}</h2>${paragraphs(prose)}</div><ol class="pain-list reveal">${bullets.map((x,j)=>`<li><span class="list-number">0${j+1}</span><p>${esc(cleanBullet(x))}</p></li>`).join('')}</ol></div><p class="pullquote reveal">${esc(d.at(-1))}</p></div></section>`}
function method(i){const d=content[i]['04'];let start=d.findIndex(x=>/^01\s/.test(x));return `<section class="section method" id="metodo"><div class="container"><div class="section-heading reveal"><div>${label(i?'03 / COMO FUNCIONA':'03 / O MÉTODO WELLNESS CORPORATE')}<h2>${esc(d[0])}</h2></div>${start>1?`<p>${esc(d[1])}</p>`:''}</div><div class="method-grid">${Array.from({length:4},(_,j)=>`<article class="method-step reveal"><span class="step-number">0${j+1}<span class="step-line"></span></span><h3>${esc(d[start+j*2].replace(/^\d+\s+/,''))}</h3><p>${esc(d[start+j*2+1])}</p></article>`).join('')}</div></div></section>`}
function audiences(){const d=content[0]['05'];return `<section class="section audiences"><div class="container"><div class="center-heading reveal">${label('04 / PARA QUEM É')}<h2>${esc(d[0])}</h2></div><div class="audiences-grid"><article class="audience reveal"><span class="audience-meta">01 / CORPORATIVO</span><h3>${esc(d[1])}</h3><p>${esc(d[2])}</p></article><article class="audience reveal"><span class="audience-meta">02 / DESENVOLVIMENTO HUMANO</span><h3>${esc(d[3])}</h3><p>${esc(d[4])}</p></article></div></div></section>`}
function services(){const d=content[0]['06'];return `<section class="section services" id="servicos"><div class="container"><div class="section-heading reveal"><div>${label('05 / NOSSAS SOLUÇÕES')}<h2>${esc(d[0])}</h2></div><p>${esc(d[1])}</p></div><div class="service-grid">${Array.from({length:4},(_,j)=>`<a class="service-card reveal" href="${urlFor(j+1)}"><div class="service-card-top"><span class="service-number">0${j+1}</span><span class="service-category">${esc(d[2+j*3])}</span></div><h3>${esc(d[3+j*3])}</h3><p>${esc(d[4+j*3])}</p><span class="service-link">Ver a solução ${arrow}</span></a>`).join('')}</div></div></section>`}
function authority(){const d=content[0]['07'];return `<section class="section authority" id="autoridade"><div class="container authority-grid"><figure class="authority-photo reveal"><img src="/assets/bruna-vilaca.webp" width="1066" height="1600" loading="lazy" alt="Bruna Vilaça, especialista em comportamento humano e estratégia corporativa"><figcaption><span class="signature">Bruna Vilaça</span><span>À FRENTE DO INSTITUTO</span></figcaption></figure><div class="authority-copy reveal">${label('06 / QUEM CONDUZ A TRANSFORMAÇÃO')}<h2>${esc(d[0])}</h2><p>${esc(d[7])}</p><div class="credentials"><div><strong>${esc(d[1])}</strong><span>${esc(d[2])}</span></div><div><strong>${esc(d[3])}</strong><span>${esc(d[4])}</span></div><div><strong>${esc(d[5])}</strong><span>${esc(d[6])}</span></div></div></div></div></section>`}
function cases(){const d=content[0]['08'];return `<section class="section cases" id="resultados"><div class="container"><div class="section-heading reveal"><div>${label('07 / RESULTADOS')}<h2>${esc(d[0])}</h2></div><p>${esc(d[1])}</p></div>${config.cases.length?`<div class="case-grid">${config.cases.map(c=>`<article><span class="eyebrow">${esc(c.sector)}</span><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p></article>`).join('')}</div>`:''}</div></section>`}
function finalCta(i){const d=content[i][i?'07':'09'];return `<section class="final-cta" id="diagnostico"><div class="container cta-panel reveal"><div class="cta-topline"><span></span><i>◆</i><span></span></div><h2>${esc(d[0])}</h2><p>${esc(d[1])}</p>${button(d[2],i)}<small>${esc(d[3])}</small><div class="cta-bottomline" aria-hidden="true"></div></div></section>`}
function deliverables(i){const d=content[i]['03'];return `<section class="section deliverables"><div class="container"><div class="section-heading reveal"><div>${label('02 / O QUE ENTREGAMOS')}<h2>${esc(d[0])}</h2></div><p>${esc(d[1])}</p></div><div class="deliverables-grid">${Array.from({length:4},(_,j)=>`<article class="delivery reveal"><span class="delivery-index">0${j+1}</span><div><h3>${esc(d[2+j*2])}</h3><p>${esc(d[3+j*2])}</p></div></article>`).join('')}</div></div></section>`}
function suitability(i){const d=content[i]['05'];return `<section class="section suitability"><div class="container intro-grid"><div class="reveal">${label('04 / PARA QUEM É')}<h2>${esc(d[0])}</h2></div><ul class="check-list reveal">${d.slice(1).map(x=>`<li><span aria-hidden="true">◆</span>${esc(cleanBullet(x))}</li>`).join('')}</ul></div></section>`}
function outcomes(i){const d=content[i]['06'];return `<section class="section outcomes"><div class="container"><div class="intro-grid"><div class="reveal">${label('05 / RESULTADO ESPERADO')}<h2>${esc(d[0])}</h2><p class="section-desc">${esc(d[1])}</p></div><ul class="check-list reveal">${d.slice(2).map(x=>`<li><span aria-hidden="true">✓</span>${esc(cleanBullet(x))}</li>`).join('')}</ul></div></div></section>`}
function faq(i){const d=content[i]['08'];return `<section class="section faq" id="perguntas"><div class="container faq-grid"><div class="reveal">${label('06 / TIRE SUAS DÚVIDAS')}<h2>${esc(d[0])}</h2></div><div class="faq-items reveal">${Array.from({length:4},(_,j)=>`<details class="faq-item" name="faq"><summary>${esc(cleanBullet(d[j*2+1]))}<span class="faq-icon" aria-hidden="true"></span></summary><div class="faq-answer"><p>${esc(d[j*2+2])}</p></div></details>`).join('')}</div></div></section>`}
function body(i){return i?pain(i)+deliverables(i)+method(i)+suitability(i)+outcomes(i)+finalCta(i)+faq(i):wellness()+pain(0)+method(0)+audiences()+services()+authority()+cases()+finalCta(0);}

for(let i=0;i<5;i++){const dir=new URL(`./dist/${routes[i]}/`,import.meta.url);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(new URL('index.html',dir),page(i,body(i)));}
console.log('5 páginas geradas.');
